name: Build Obfuscate cmliu_edge

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"  # 每天凌晨3点自动运行
  workflow_dispatch:     # 支持手动运行

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
          sudo apt-get install -y unzip

      - name: Clean existing obfuscated files
        run: |
          rm -f _worker.js* origin.js

      - name: Download latest cmliu_edge worker
        run: |
          wget https://raw.githubusercontent.com/cmliu/edgetunnel/refs/heads/main/_worker.js -O origin.js

      - name: Obfuscate JavaScript
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'base64' \
          --string-array-threshold 0.75 \
          --transform-object-keys true \
          --self-defending false \
          --simplify true

      - name: Check file changes
        id: changes
        run: |
          if git diff --quiet --exit-code _worker.js; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in _worker.js"
          fi

      - name: Commit and push changes
        if: ${{ steps.changes.outputs.has_changes == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest cmliu_edge'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: _worker.js
