name: Build Obfuscate cmliu_edge

on:
  push:
    branches:
      - main  # 主分支推送时触发
  schedule:
    - cron: "0 3 * * *"  # 每天凌晨3点自动运行
  workflow_dispatch:     # 支持在GitHub网页手动触发工作流

permissions:
  contents: write  # 授予工作流写入仓库的权限

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版Ubuntu系统

    steps:
      # 步骤1：检出仓库代码
      - name: Check out the code
        uses: actions/checkout@v4

      # 步骤2：设置Node.js环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      # 步骤3：安装所需依赖
      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
          sudo apt-get install -y unzip

      # 步骤4：清理旧文件
      - name: Clean existing obfuscated files
        run: |
          rm -f _worker.js* origin.js

      # 步骤5：下载最新worker脚本_worker.js重命名为origin.js
      - name: Download latest cmliu_edge worker
        run: |
          wget https://raw.githubusercontent.com/cmliu/edgetunnel/refs/heads/main/_worker.js -O origin.js

      # 步骤6：执行JavaScript混淆
      - name: Obfuscate JavaScript
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'base64' \
          --string-array-threshold 0.75 \
          --transform-object-keys true \
          --self-defending false \
          --simplify true

      # 步骤7：检查文件变更
      - name: Check file changes
        id: changes
        run: |
          if git diff --quiet --exit-code _worker.js; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in _worker.js"
          fi

      # 步骤8：条件提交变更
      - name: Commit and push changes
        if: ${{ steps.changes.outputs.has_changes == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest cmliu_edge'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: _worker.js
